#!/usr/bin/env python3

import panflute as pf

def action(elem, doc):
    pass

def finalize(doc):
    if doc.format == 'latex':
        package = pf.MetaInlines(
            pf.RawInline(r'\usepackage{zzz}', format='latex')
        )
        if 'header-includes' not in doc.metadata:
            doc.metadata['header-includes'] = pf.MetaList(package)
        else:
            # Ensure it's a list
            if not isinstance(doc.metadata['header-includes'], pf.MetaList):
                doc.metadata['header-includes'] = pf.MetaList(doc.metadata['header-includes'])
            # Append 
            doc.metadata['header-includes'].append(package)
    
if __name__ == '__main__':
    pf.run_filter(action, finalize=finalize, doc=None)